DROP TABLE IF EXISTS USERS;
DROP INDEX IF EXISTS EMAIL_INDEX;
DROP TABLE IF EXISTS ELIGIBILITY_METADATA;

CREATE TABLE ELIGIBILITY_METADATA (
    ID SERIAL PRIMARY KEY,
    FILE_URL VARCHAR(255) NOT NULL,
    EMPLOYER_NAME VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS EMPLOYER_NAME
ON ELIGIBILITY_METADATA (EMPLOYER_NAME);

CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    FULLNAME VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    BIRTHDATE TIMESTAMP NOT NULL,
    SALARY DECIMAL(10, 2) NOT NULL,
    EMPLOYER_ID INTEGER NOT NULL,
    CONSTRAINT FK_EMPLOYER_NAME
        FOREIGN KEY (EMPLOYER_ID)
            REFERENCES ELIGIBILITY_METADATA(ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS EMAIL_INDEX
ON USERS (EMAIL);